FROM eclipse-temurin:17-jdk-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring
VOLUME /tmp
EXPOSE 8080

ENV MYSQL_HOST=host
ENV MYSQL_USERNAME=username
ENV MYSQL_PASSWORD=password


COPY target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]